Add docker_network options
senorsmile/ansible-docker_deploy pull request #9
Opened 2019-07-16 22:32 UTC by marchenm

This pr allows docker_networks to be specified without containers, but also allows for containers for backwards compatibility.

Also adds advanced network options.

2019-07-17 01:19 UTC, senorsmile commented
It looks good to me.  Have you tested it on real infra yet?  The "when: " clauses may need to be modified if they don't work as is.  I'd like to see end results of when docker_networks.containers is defined, and also when it is not.

2019-07-17 02:17 UTC, marchenm commented
I've fixed the when statements and tested both cases.

2019-07-17 03:02 UTC, senorsmile requested changes

2019-07-17 03:02 UTC, senorsmile commented on tasks/main.yml
> +    when: docker_networks | selectattr('containers', 'undefined')
I see what you're doing there!  

The easier way to specify this (and safer) would be:
```
when:
  - docker_networks is defined
  - docker_networks.containers is defined
```

the list passed to when is a logical AND

2019-07-17 03:02 UTC, senorsmile commented on tasks/main.yml
> +    when: docker_networks | selectattr('containers', 'defined')
and for this one
```
when: ( 
    docker_networks is undefined
    or
    docker_networks.containers is undefined
  )
```

2019-07-23 23:17 UTC, marchenm commented
Fixed. I've tested both cases and it works.

2019-07-24 16:19 UTC, senorsmile approved these changes
lgtm :+1:

2019-07-24 16:20 UTC, merged